### ISSUE TITLE
API modifications

### ISSUE THREAD

**Issue by Victoire-Rabeau** [Prophecy-eip/Backend#27]
# Api modifications

## Ids

- [ ] Add objects id in

## Retrieve data

- [ ] Rename get route to retrieve objects ids
```
get -> lookup
```
- [ ] Add the number of objects to retrieve + token to retrieve the next objects

## Usernames

- [ ] make usernames unique and use as id

**Comment by n0no123** [comment]
I didn't find a route for a forgotten password.

**Comment by Victoire-Rabeau** [comment]
> 

Done :)
